[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd frontend && rm -rf node_modules && npm install"]

[phases.build]
cmds = ["cd frontend && npm run build && cp -r dist/* ../backend/static/"]
